FROM apache/airflow:2.7.1-python3.10

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    tesseract-ocr \
    tesseract-ocr-rus \
    tesseract-ocr-eng \
    tesseract-ocr-ukr \
    poppler-utils \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
# Устанавливаем CPU-версию PyTorch, чтобы сэкономить 1.5 ГБ трафика и ускорить запуск
RUN pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu torch==2.5.1

# Копируем и устанавливаем остальные зависимости
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
